### ISSUE TITLE
Add Tutorial Notebooks to MkDocs 

### ISSUE THREAD

**Issue by benjaminpope** [LouisDesdoigts/dLux#81]
We have some great tutorial notebooks - it will be good to include these in the MkDocs path (much along the lines of the "Fitting a Carbon Box Model" section on https://sharmallama.github.io/ticktack/).

**Comment by Jordan-Dennis** [comment]
Ok I've added some of them now. I just moved the `notebooks` folder into `docs/notebooks` and linked in a selection.

**Comment by Jordan-Dennis** [comment]
@benjaminpope can this issue be resolved now or did you want to wait for the pull request to go through?

**Comment by benjaminpope** [comment]
I think we wait til the pull request. I'm still not really able to build docs for JWST until the Hex segments are committed to `main`, and the phase retrieval kinda sucks unless we can build better apertures with spiders (pupil cannot be inversion-symmetric), so building the required docs needs those too.

**Comment by benjaminpope** [comment]
@Jordan-Dennis we just need to add

- [ ] JWST PSF demo
- [ ] Fresnel focus optimization

notebooks and I think we are done with doc examples.

**Comment by LouisDesdoigts** [comment]
Closing this as the JWST code will live elsewhere and the Fresnel code will not be finished for a while.
